### ISSUE TITLE
Hide "X" button on the last remaining column

### ISSUE THREAD

**Issue by alyuev** [tigran123/urantia-book-explorer#97]

**Comment by tigran123** [comment]
No, that is not necessary, because that would mean enforcing a specific usage policy for no good reason. You can have between 0 and 4 texts in parallel and the value 0 is perfectly valid. E.g. it can correspond to the person doing the searches (without needing more than one paragraph of context) or just reading the NOTES section without referring to the places of origins of those notes in the text.

**Comment by alyuev** [comment]
Ok. Then I can reformulate the task this way - make the button hide on the last remaining column (not only text-columns). Because now you can close all the columns!

**Comment by tigran123** [comment]
Yes, that is a reasonable limitation, i.e. there should always be at least one visible column, I agree.

**Comment by tigran123** [comment]
Fixed by #98
